language: go

go:
  - 1.6.3

notifications:
  email: false

before_install:
  - go get github.com/golang/lint/golint

script:
  - $HOME/gopath/bin/golint ./...
  - go vet -x ./...
  - go test -v ./...
  